### ISSUE TITLE
TypeError: argument should be a str object or an os.PathLike object returning str, not <class 'bytes'>

### ISSUE THREAD

**Issue by Rookiee111** [stlukey/whispercpp.py#15]
>>> w = Whisper('tiny')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "whispercpp.pyx", line 89, in whispercpp.Whisper.__init__
  File "whispercpp.pyx", line 34, in whispercpp.download_model
  File "whispercpp.pyx", line 31, in whispercpp.model_exists
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pathlib.py", line 851, in joinpath
    return self._make_child(args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pathlib.py", line 616, in _make_child
    drv, root, parts = self._parse_args(args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pathlib.py", line 583, in _parse_args
    raise TypeError(
TypeError: argument should be a str object or an os.PathLike object returning str, not <class 'bytes'>

I am facing this issue, when trying initialise whisper object with "tiny" model

**Comment by Rookiee111** [comment]
duplicate issue, closing it
